version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: '10'
    docker:
      - image: circleci/node:<< parameters.image >>
  cypress:
    docker:
      - image: cypress/base:10

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        # - cache-{{ checksum "package.json" }}
        - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
  install_node_modules: &install_node_modules
    run:
      name: Install Npm Dependencies
      command: npm ci

  save_cache: &save_cache
    save_cache:
      name: Save Npm Package Cache
      # key: cache-{{ checksum "package.json" }}
      key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      paths:
        # - ~/.npm
        # - ~/.cache
        - ./node_modules

jobs:
  install:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
  build_and_test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build Dist
          command: npm run test && npm run build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .nuxt
  # unit_test:
  #   executor: cypress
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: /home/circleci/project
  #     - <<: *restore_cache
  #     - <<: *install_node_modules
  #     - run:
  #         name: Run Unit Tests
  #         command: npm run test
  e2e_test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - <<: *restore_cache
      - <<: *install_node_modules
      # - run: npm i cypress
      - run: npm run cy:verify
      - run:
          name: Run Nuxt App
          command: npm start
          background: true
      - run:
          name: Run Cypress
          command: npm run cy:run
  deploy:
    executor: cypress
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: install netlify cli
          command: sudo npm install netlify-cli -g
      - run:
          name: deploy site to netlify
          command: netlify deploy -dir=~/.nuxt/dist -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build_and_test:
          requires:
            - install
      # - unit_test:
      #     requires:
      #       - build_and_lint
      - e2e_test:
          requires:
            - build_and_test
      - deploy:
          context: NuxtNetlify
          requires:
            - e2e_test
# version: 2
# jobs:

#   test:
#     branches:
#       ignore:
#         - master
#     docker:
#       - image: cypress/base:10
#     steps:
#       - checkout
#       # restore folders with npm dependencies and Cypress binary
#       - restore_cache:
#           keys:
#             - cache-{{ checksum "package.json" }}
#       # install npm dependencies and Cypress binary
#       # if they were cached, this step is super quick
#       - run:
#           name: Install dependencies
#           command: npm ci
#       - run: npm run cy:verify
#       # save npm dependencies and Cypress binary for future runs
#       - save_cache:
#           key: cache-{{ checksum "package.json" }}
#           paths:
#             - ~/.npm
#             - ~/.cache
#       # start server before starting tests
#       - run:
#           name: Build Nuxt App
#           command: npm run build
#       - run:
#           name: Run Nuxt App
#           command: npm start
#           background: true
#       - run:
#           name: Run Cypress
#           command: npm run cy:run:record

# workflows:
#   version: 2
#   build:
#     jobs:
#       - test
