version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # - cypress/install:
      #     build: npm run build
      - cypress/run:
          start: npm run build
          record: true
# version: 2
# jobs:
#   test:
#     docker:
#       - image: cypress/base:10
#     steps:
#       - checkout
#       # restore folders with npm dependencies and Cypress binary
#       - restore_cache:
#           keys:
#             - cache-{{ checksum "package.json" }}
#       # install npm dependencies and Cypress binary
#       # if they were cached, this step is super quick
#       - run:
#           name: Install dependencies
#           command: npm ci
#       - run: npm run cy:verify
#       # save npm dependencies and Cypress binary for future runs
#       - save_cache:
#           key: cache-{{ checksum "package.json" }}
#           paths:
#             - ~/.npm
#             - ~/.cache
#       # start server before starting tests
#       - run:
#           name: Build Nuxt App
#           command: npm run build
#       - run:
#           name: Run Nuxt App
#           command: npm start
#           background: true
#       - run:
#           name: Run Cypress E2E
#           command: npm run cy:run:record

# workflows:
#   version: 2
#   build:
#     jobs:
#       - test
